registry:
    class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
    zkclient: dep:kazoo


event_system:
    class: lymph.events.kombu:KombuEventSystem
    transport: amqp
    hostname: rabbitmq


dependencies:
    kazoo:
        class: kazoo.client:KazooClient
        hosts: zk
 
 
instances:
    inbound:
        command: lymph instance --config=inbound/inbound.yml --reload --debug --loglevel=DEBUG

    ingesting:
        command: lymph instance --config=ingesting/ingesting.yml --reload --debug --loglevel=DEBUG

    crunching:
       command: lymph instance --config=crunching/crunching.yml --reload --debug --loglevel=DEBUG

    barometer:
        command: lymph instance --config=barometer/barometer.yml --reload --debug --loglevel=DEBUG
