registry:
    class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
    zkclient: dep:kazoo


event_system:
    class: lymph.events.kombu:KombuEventSystem
    transport: amqp
    hostname: rabbitmq


dependencies:
    kazoo:
        class: kazoo.client:KazooClient
        hosts: zk


instances:
    inbound:
        command: lymph instance --conf=inbound.yml --reload --debug --loglevel=info
        numprocesses: 1
